industry_location_panel.dta: industry_location_panel.do ../clean/industry-employment/industry-employment.dta crosswalk/2digit_names.csv occupation/naics_risk.csv ../clean/cbp/zip_code_business_patterns.dta
	stata -b do $<
