visit-naics-zip.dta: read.do ../../../input/safegraph-industry-location/naics-zip-02.csv ../../../input/safegraph-industry-location/naics-zip-05.csv ../../derived/crosswalk/naics2industry.csv
	stata -b do $<
