download:
	wget "https://www.onetonline.org/find/descriptor/result/4.C.1.a.4/Contact_With_Others.csv?fmt=csv&a=1" -O Contact_With_Others.csv
	wget "https://www.onetonline.org/find/descriptor/result/4.C.1.b.1.f/Deal_With_External_Customers.csv?fmt=csv&a=1" -O Deal_With_External_Customers.csv
	wget "https://www.onetonline.org/find/descriptor/result/4.C.1.a.2.l/Face-to-Face_Discussions.csv?fmt=csv&a=1" -O Face-to-Face_Discussions.csv
	wget "https://www.onetonline.org/find/descriptor/result/4.C.1.b.1.e/Work_With_Work_Group_or_Team.csv?fmt=csv&a=1" -O Work_With_Work_Group_or_Team.csv
	wget "https://www.onetonline.org/find/descriptor/result/4.C.2.c.1.b/Exposed_to_Disease_or_Infections.csv?fmt=csv&a=1" -O Exposed_to_Disease_or_Infections.csv
	wget "https://www.onetonline.org/find/descriptor/result/4.C.2.a.3/Physical_Proximity.csv?fmt=csv&a=1" -O Physical_Proximity.csv 