zbp17detail.txt: zbp17detail.zip
	unzip $<
	rm $<
download:
	wget -Nnd https://www2.census.gov/programs-surveys/cbp/datasets/2017/zbp17detail.zip
	wget -Nnd https://www2.census.gov/programs-surveys/cbp/technical-documentation/records-layouts/2017_record_layouts/zip_code_industry_detail_record_layout_2017.txt
	wget -Nnd https://www2.census.gov/programs-surveys/cbp/technical-documentation/reference/naics-descriptions/naics2017.txt
	wget -Nnd https://www2.census.gov/geo/docs/maps-data/data/rel/zcta_county_rel_10.txt
