html/social-distancing.html: CEPR.tex content.tex abstract.tex socdist.bib fig1.eps fig2.eps fig3.eps fig4.eps
	engrafo CEPR.tex html/
%.tex: overleaf/%.tex
	cp $< $@
%.eps: overleaf/%.eps
	cp $< $@
%.bib: overleaf/%.bib
	cp $< $@
social-distancing.pdf: overleaf/main.pdf
	cp $< $@